export const DEFAULT_CONFIG_VALUES = {
    'sectionStartMarker': 'h1',
    'sectionTitleMarker': 'h1',
    'chapterStartMarker': 'h2',
    'chapterTitleMarker': 'h2',
    'flowElement': 'document.body',
    'flowTo': 'document.body',
    'alwaysEven': true,
    'enableFrontmatter': true,
    //        'enableTableOfFigures': false,
    //        'enableTableOfTables': false,
    //        'enableMarginNotes': false,
    //        'enableCrossReferences': true,
    //        'enableWordIndex': true,
    //        'bulkPagesToAdd': 50,
    //        'pagesToAddIncrementRatio': 1.4,
    'frontmatterContents': '',
    'numberPages': true,
    'footnoteSelector': '.pagination-footnote',
    'pagebreakSelector': '.pagination-pagebreak',
    'topfloatSelector': '.pagination-topfloat',
    //        'marginnoteSelector': '.pagination-marginnote',
    //        'maxPageNumber': 10000,
    //        'columnSeparatorWidth': 0.09,
    'outerMargin': 0.5,
    'innerMargin': 0.8,
    'contentsTopMargin': 0.8,
    'headerTopMargin': 0.3,
    'contentsBottomMargin': 0.8,
    'pagenumberBottomMargin': 0.3,
    'pageHeight': 8.3,
    'pageWidth': 5.8,
    //        'marginNotesWidth': 1.5,
    //        'marginNotesSeparatorWidth': 0.09,
    //        'marginNotesVerticalSeparatorWidth': 0.09,
    'lengthUnit': 'in'
}
